apiVersion: v1
kind: Service
metadata:
  name: wil42-playground
  namespace: dev
spec:
  selector:
    app: wil42-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30002
  type: NodePort
